ktor {
    deployment {
        port = 8080
        port = ${?PORT}
    }
    application {
        modules = [ com.thetower.ApplicationKt.module ]
    }
}

thetower {
    persistence {
        sqlite {
            enabled = true
            path = "data/thetower.db"
        }
    }
    executor {
        playwright {
            browser = "chromium"
            browser = ${?THETOWER_BROWSER}
            headless = true
            headless = ${?THETOWER_HEADLESS}
            defaultTimeoutMs = 10000
            defaultTimeoutMs = ${?THETOWER_DEFAULT_TIMEOUT_MS}
        }
    }
}
