ktor {
    deployment {
        port = 8080
        port = ${?PORT}
    }
    application {
        modules = [ com.thetower.ApplicationKt.module ]
    }
}

thetower {
    persistence {
        sqlite {
            enabled = true
            path = "data/thetower.db"
        }
    }
}
